PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS intake_sessions(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,state_json TEXT NOT NULL DEFAULT '{}',expires_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS cases(id INTEGER PRIMARY KEY AUTOINCREMENT,reporter_id TEXT NOT NULL,accused_id TEXT NOT NULL,category TEXT NOT NULL,route_tier TEXT NOT NULL,summary TEXT,location TEXT,timing TEXT,resolution_json TEXT NOT NULL DEFAULT '{}',channel_id TEXT,status TEXT NOT NULL DEFAULT 'OPEN',created_at INTEGER NOT NULL,closed_at INTEGER);
CREATE TABLE IF NOT EXISTS witnesses(id INTEGER PRIMARY KEY AUTOINCREMENT,case_id INTEGER NOT NULL,user_id TEXT NOT NULL,witness_type TEXT NOT NULL,dm_delivered INTEGER NOT NULL DEFAULT 0,UNIQUE(case_id,user_id));
CREATE TABLE IF NOT EXISTS appeals(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'OFFERED',channel_id TEXT,reentry_pending INTEGER NOT NULL DEFAULT 0,role_lock INTEGER NOT NULL DEFAULT 0,application_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL,closed_at INTEGER);
CREATE UNIQUE INDEX IF NOT EXISTS one_open_appeal ON appeals(user_id) WHERE status IN('OFFERED','REENTRY_PENDING','OPEN','SUBMITTED','REVIEW');
CREATE TABLE IF NOT EXISTS polls(id INTEGER PRIMARY KEY AUTOINCREMENT,type TEXT NOT NULL,case_id INTEGER,appeal_id INTEGER,channel_id TEXT,message_id TEXT,status TEXT NOT NULL DEFAULT 'OPEN',closes_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS votes(poll_id INTEGER NOT NULL,voter_id TEXT NOT NULL,choice TEXT NOT NULL,PRIMARY KEY(poll_id,voter_id));
